p1:
	@gcc -Wall -Wextra -Werror -I.. -L.. -lft -x c ./part1/part1.test ./part1/ft_isalnum.test ./part1/ft_isalpha.test ./part1/ft_isascii.test ./part1/ft_isdigit.test ./part1/ft_isprint.test ./part1/ft_strlen.test ./part1/tools.test -o p1.out

p2:
	@gcc -Wall -Wextra -Werror -I.. -L.. -lft -x c ./part2/part2.test ./part2/ft_bzero.test ./part2/ft_memchr.test ./part2/ft_strchr.test ./part2/ft_strrchr.test ./part2/ft_tolower.test ./part2/ft_toupper.test ./part2/tools.test -o p2.out

p3:
	@gcc -Wall -Wextra -Werror -I.. -L.. -lft -x c ./part3/part3.test ./part3/ft_memcmp.test ./part3/ft_memcpy.test ./part3/ft_memmove.test ./part3/ft_strcat.test ./part3/ft_strcmp.test ./part3/ft_strcpy.test ./part3/ft_strstr.test ./part2/tools.test -o p3.out

p4:
	@gcc -Wall -Wextra -Werror -I.. -L.. -lft -x c ./part4/part4.test ./part4/ft_atoi.test ./part4/ft_memccpy.test ./part4/ft_strdup.test ./part4/ft_strlcat.test ./part4/ft_strncmp.test ./part4/ft_strncat.test ./part4/ft_strncpy.test ./part4/ft_strnstr.test ./part2/tools.test -o p4.out

p5:
	@gcc -Wall -Wextra -Werror -I.. -L.. -lft -x c ./part5/part5.test ./part5/ft_memalloc.test ./part5/ft_putchar.test ./part5/ft_putstr.test ./part5/ft_putendl.test ./part5/ft_putnbr.test ./part5/ft_strnew.test ./part5/ft_strdel.test ./part5/ft_strclr.test ./part5/ft_strequ.test ./part5/ft_strnequ.test ./part5/ft_strsub.test ./part5/ft_strjoin.test ./part5/ft_putchar_fd.test ./part5/ft_putstr_fd.test ./part5/ft_putendl_fd.test ./part5/ft_putnbr_fd.test ./part2/tools.test -o p5.out

p6:
	@gcc -Wall -Wextra -Werror -I.. -L.. -lft -x c ./part6/part6.test ./part6/ft_itoa.test ./part6/ft_memdel.test ./part6/ft_striter.test ./part6/ft_striteri.test ./part6/ft_strmap.test ./part6/ft_strmapi.test ./part6/ft_strsplit.test ./part6/ft_strtrim.test ./part6/ft_memset.test ./part2/tools.test -o p6.out

bonus:
	@gcc -Wall -Wextra -Werror -I.. -L.. -lft -x c ./bonuslst/bonuslst.test ./part2/tools.test -o bonus.out

all: p1 p2 p3 p4 p5 p6 bonus
